services:

  db:
    image: postgres:15

    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ecommerce

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      retries: 5
      timeout: 5s

  app:
    build: .
    container_name: app 
    ports:
      - "3000:3000"

    env_file:
      - .env

    depends_on:
      db:
        condition: service_healthy