name: Lab 3 Grading

on: [push]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create KinD Cluster
        uses: helm/kind-action@v1.12.0
        with:
          cluster_name: kind

      - name: Build and Pull images
        run: |
          docker build -t ecommerce-app:latest .
          # Викачуємо базу заздалегідь (це швидше)
          docker pull postgres:15-alpine

      - name: Load images into KinD
        run: |
          kind load docker-image ecommerce-app:latest --name kind
          kind load docker-image postgres:15-alpine --name kind

      - name: Deploy to Kubernetes
        run: kubectl apply -f k8s/

      - name: Wait for Postgres
        run: kubectl rollout status deployment/postgres --timeout=120s

      - name: Wait for App
        run: kubectl rollout status deployment/ecommerce-app --timeout=120s

      - name: Run Master Validation Script
        if: always()
        run: |
          chmod +x ./tests/lab3_test.sh
          ./tests/lab3_test.sh